
server:
  port: 8001

spring:
  application:
    name: dl-proxy

  profiles:
    active: dev
    include:
      - app
  devtools:
    restart:
      enabled: false

#mybatis:
#  type-aliases-package:
#    - com.c332030.mmm.entity
#    - com.c332030.mmm.model
#    - com.c332030.mmm.dao
