
server:
  port: 8001

spring:
  application:
    name: dl-proxy

  profiles:
    active: dev
    include:
      - log-file

  devtools:
    restart:
      enabled: false

logging:
  level:
    root: info
