
name: build

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: java -version
      - uses: actions/cache@v2
        with:
          key: gradle1
          path: |
            ~/.gradle/wrapper
            ~/.gradle/jdks
            ~/.gradle/caches
      - run: ls -alh ~/.gardle && ls -alh ~/.gardle/jdks
      - name: build
        run: ${{ secrets.GRADLEW }} build
      - name: init ssh
        run: ${{ secrets.INIT_SSH }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: deploy
        run: ${{ secrets.BUILD_DEPLOY }}
