
name: deploy

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  deploy:
    uses: cc332030/gradle/.github/workflows/deploy.yml@master
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
    with:
      origin-path: build/libs/boot.jar
      remote-path: /home/program/${REPOSITORY_NAME}/boot.jar
      prepare-command: docker stop ${REPOSITORY_NAME}
      action-command: sh /home/program/${REPOSITORY_NAME}/install.sh
