
name: deploy

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-deploy:
    name: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: cc332030/gradle/.github/workflows/gradle.yml@master
        with:
          command: sh gradlew build
      - name: deploy
        uses: cc332030/linux/.github/workflows/deploy.yml@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          ORIGIN_PATH: build/libs/boot.jar
          REMOTE_PATH: /home/program/${REPOSITORY_NAME}/boot.jar
          PREPARE_COMMAND: docker stop ${REPOSITORY_NAME}
          ACTION_COMMAND: sh /home/program/${REPOSITORY_NAME}/install.sh
