
name: deploy

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: gradle
          path: |
            ~/.gradle/wrapper
            ~/.gradle/jdks
            ~/.gradle/caches
      - run: sh gradlew build
      - uses: cc332030/init-ssh-action@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - id: vars
        run: echo '::set-output name=REPOSITORY_NAME::$(echo "${GITHUB_REPOSITORY}" | cut -d / -f 2 | xargs -I {} basename {} .git)'
      - uses: cc332030/deploy-action@main
        env:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          ORIGIN_PATH: build/libs/boot.jar
          REMOTE_PATH: /home/program/${{ steps.vars.outputs.REPOSITORY_NAME }}/boot.jar
          PREPARE_COMMAND: docker stop ${{ steps.vars.outputs.REPOSITORY_NAME }}
          ACTION_COMMAND: sh /home/program/${{ steps.vars.outputs.REPOSITORY_NAME }}/install.sh
