
name: mirror

on: push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: cc332030/git-mirror-action@github
        timeout-minutes: 30
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt-openj9'
      - name: Build with Gradle
        run: ./gradlew build && pwd && ls -alh
